// This code was generated by FFIG <http://ffig.org>.
// Manual edits will be lost.
#include <boost/python.hpp>
#include "Tree.h"
#include <boost/python/exception_translator.hpp>
#include <exception>

BOOST_PYTHON_MODULE(Tree_py)
{
  using namespace boost::python;
  
  class_<Tree>("Tree", init<int>())
    .def("left_subtree", &Tree::left_subtree, return_internal_reference<1, with_custodian_and_ward_postcall<0, 1> >())
    .def("right_subtree", &Tree::right_subtree, return_internal_reference<1, with_custodian_and_ward_postcall<0, 1> >())
    .def("data", &Tree::data)
    .def("set_data", &Tree::set_data)
  ;

}
