# clone directory
clone_folder: c:\projects\ffig

install:
  - set PATH="C:\Program Files\LLVM\bin";%PATH%
  - git submodule update --init
  - C:\Python36-x64\python -m pip install jinja2 nose

# scripts to run before build (We use this to build and run tests)
before_build:
  - cd c:\projects\ffig
  
build_script:
  - python scripts\build.py -t --python-path "C:\\Python36-x64\\python"

