sudo: required

services:
  - docker

install:
  - docker build -t ffig_cont .

script:
  - docker run ffig_cont /bin/bash -c "export PATH=$PATH:/home/c-api-user/.local/bin && cd ../ && ./run_tests.sh"
