sudo: required

language: python

cache:
  directories:
    - /home/travis/docker/

env:
  global:
    - DOCKER_CACHE_FILE=/home/travis/docker/cache.tar.gz
   
services:
  - docker
  
before_install:
  - if [ -f ${DOCKER_CACHE_FILE} ]; then gunzip -c ${DOCKER_CACHE_FILE} | docker load; fi

install:
  - docker build -t ffig_cont .

script:
  - docker run ffig_cont /bin/bash -c "cd ../ && ./run_tests.sh"
  - mkdir -p $(dirname ${DOCKER_CACHE_FILE}) ; docker save $(docker history -q ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} | grep -v '<missing>') | gzip > ${DOCKER_CACHE_FILE};

notifications:
  slack:
    rooms:
      - c-api:ZTxxqvEcr25iaaB8XBS7luaA#general
