# Modify this line to test Travis Integration .... 
sudo: required

language: python

matrix:
  include:
    - os: linux
      sudo: required
      env:
        global:
          - DOCKER_REPOSITORY=jbcoe/ffig
          - DOCKER_CACHE_FILE=/home/travis/docker/cache.tar.gz
      services:
        - docker
      install:
        - ./scripts/travis-ci/install_linux.sh
      before_install:
        - pip install pep8
      script:
        - ./scripts/travis-ci/build_linux.sh
        - ./scripts/codechecks.py
    - os: osx
      install:
        - ./scripts/travis-ci/install_osx.sh
      script:
        - ./scripts/travis-ci/build_osx.sh

notifications:
  slack:
    rooms:
      - c-api:ZTxxqvEcr25iaaB8XBS7luaA#travis-ci
