sudo: required

services:
  - docker

before_install:
  - docker build -t ffig_cont .
  - docker ps -a
  - docker run ffig_cont /bin/bash -c "export PATH=$PATH:/home/c-api-user/.local/bin && cd ../ && ./run_tests.sh"


script:
  - ./run_tests.sh