sudo: required

language: python

services:
  - docker

install:
  - docker build -t ffig_cont .

script:
  - docker run -e PATH=$PATH:/home/c-api-user/.local/bin ffig_cont /bin/bash -c "cd ../ && ./run_tests.sh"
