sudo: required

language: python

services:
  - docker

install:
  - docker build -t ffig_cont .

script:
  - docker run ffig_cont /bin/bash -c "cd ../ && ./scripts/build.py -t"

notifications:
  slack:
    rooms:
      - c-api:ZTxxqvEcr25iaaB8XBS7luaA#general
