sudo: required

language: python

services:
  - docker

install:
  - if [ ${TRAVIS_PULL_REQUEST} = "false" ]; then
      git checkout $TRAVIS_BRANCH;
    else
      git checkout -b $TRAVIS_PULL_REQUEST_BRANCH;
    fi
  - docker build -t ffig_cont .

script:
  - docker run ffig_cont /bin/bash -c "export PATH=$PATH:/home/c-api-user/.local/bin && cd ../ && ./run_tests.sh"
