language: cpp
sudo: false

matrix:
  include:
    - os: linux
      compiler: clang
      addons: &clang38
        apt:
          sources: ['llvm-toolchain-precise-3.8', 'ubuntu-toolchain-r-test']
          packages: ['clang-3.8']
      env: COMPILER='clang++-3.8'

install:
  - pip install --user clang django

before_script: 
  - export CXX=${COMPILER}
  - export LD_LIBRARY_PATH=`find /usr/libexec -name libclang.so`

script: ${TRAVIS_BUILD_DIR}/run_tests.sh

