language: cpp
sudo: false

matrix:
  include:
    - os: linux
      compiler: clang
      addons: &clang38
        apt:
          sources: ['llvm-toolchain-precise-3.8', 'ubuntu-toolchain-r-test']
          packages: ['clang-3.8']
      env: COMPILER='clang++-3.8'

install:
  - pip install clang

before_script: export CXX=${COMPILER}

script: ${TRAVIS_BUILD_DIR}/run_tests.sh

