# Modify this line to test Travis Integration ... 
sudo: required

language: python

cache:
  directories:
    - /home/travis/docker/

env:
  global:
    - DOCKER_REPOSITORY=jbcoe/ffig
    - DOCKER_CACHE_FILE=/home/travis/docker/cache.tar.gz
   
services:
  - docker
  
before_install:
  - if [ -f ${DOCKER_CACHE_FILE} ]; then gunzip -c ${DOCKER_CACHE_FILE} | docker load || true; fi

install:
  - docker build -t ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} .

script:
  - docker run ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} /bin/bash -c "./scripts/build.py -t"
  - docker run ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} /bin/bash -c "./scripts/build.py -t --python-path python3"

after_success:
  - mkdir -p $(dirname ${DOCKER_CACHE_FILE}) ; docker save $(docker history -q ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} | grep -v '<missing>') | gzip > ${DOCKER_CACHE_FILE};
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT};
    fi

notifications:
  slack:
    rooms:
      - c-api:ZTxxqvEcr25iaaB8XBS7luaA#travis-ci
